### ISSUE TITLE
Exception getting DebugView of expression with nested lambdas

### ISSUE THREAD

**Issue by avonwyss** [zspitz/ExpressionTreeToString#79]
**Describe the bug**  
When trying to get DebugView:
```
System.ArgumentOutOfRangeException
'count' must be non-negative.
Parameter name: count
   at System.String.CtorCharCount(Char c, Int32 count)
   at ExpressionTreeToString.WriterVisitorBase.WriteEOL(Boolean dedent)
   at ExpressionTreeToString.DebugViewWriterVisitor.Out(Flow before, String s, Flow after)
   at ExpressionTreeToString.DebugViewWriterVisitor.WriteLambdaFull(LambdaExpression expr)
   at ExpressionTreeToString.DebugViewWriterVisitor.WriteLambda(LambdaExpression expr)
   at ExpressionTreeToString.BuiltinsWriterVisitor.writeExpression(Expression expr)
   at ExpressionTreeToString.BuiltinsWriterVisitor.WriteNodeImpl(Object o, Boolean parameterDeclaration, Object metadata)
   at ExpressionTreeToString.DebugViewWriterVisitor.WriteNodeImpl(Object o, Boolean parameterDeclaration, Object metadata)
   at ExpressionTreeToString.WriterVisitorBase.WriteNode(String pathSegment, Object o, Boolean parameterDeclaration, Object metadata)
   at ExpressionTreeToString.WriterVisitorBase..ctor(Object o, OneOf`2 languageArg, IEnumerable`1 insertionPointKeys, Boolean hasPathSpans)
   at ExpressionTreeToString.BuiltinsWriterVisitor..ctor(Object o, OneOf`2 languageArg, IEnumerable`1 insertionPointKeys, Boolean hasPathSpans)
   at ExpressionTreeToString.DebugViewWriterVisitor..ctor(Object o, Boolean hasPathSpans)
   at ExpressionTreeToString.Renderers.<>c.<.cctor>b__6_6(Object o, OneOf`2 languageArg, Boolean usePathSpans)
   at ExpressionTreeToString.Renderers.Invoke(OneOf`2 rendererArg, Object o, OneOf`2 language)
   at ExpressionTreeToString.ExpressionExtension.ToString(Expression expr, OneOf`2 rendererArg, OneOf`2 language)
```

**To Reproduce**  
The following is the DebugView of the failing expression in VS:
```
.Lambda #Lambda1<System.Func`2[SomeType,System.Threading.Tasks.ValueTask`1[System.Double]]>(SomeType $var1)
{
    .New System.Threading.Tasks.ValueTask`1[System.Double](.Call $var1.Lambda(
            10D,
            .Lambda #Lambda2<System.Func`2[System.Double,System.Double]>))
}

.Lambda #Lambda2<System.Func`2[System.Double,System.Double]>(System.Double $x) {
    .Call $var1.Lambda(
        20D,
        .Lambda #Lambda3<System.Func`2[System.Double,System.Double]>)
}

.Lambda #Lambda3<System.Func`2[System.Double,System.Double]>(System.Double $y) {
    .Call $var1.Max(.Call $var1.Array(.NewArray System.Double[] {
                $x,
                $y,
                0D
            }))
}
```

The following are the factory methods in C#:
```
// using static System.Linq.Expressions.Expression

var y = Parameter(
    typeof(double),
    "y"
);
var x = Parameter(
    typeof(double),
    "x"
);
var $var0 = Parameter(
    typeof(TestContainer)
);

Lambda(
    New(
        typeof(ValueTask<double>).GetConstructor(new[] { typeof(double) }),
        Call($var0,
            typeof(SomeType).GetMethod("Lambda"),
            Constant(10),
            Lambda(
                Call($var0,
                    typeof(SomeType).GetMethod("Lambda"),
                    Constant(20),
                    Lambda(
                        Call($var0,
                            typeof(SomeType).GetMethod("Max"),
                            Call($var0,
                                typeof(SomeType).GetMethod("Array"),
                                NewArrayInit(
                                    typeof(double),
                                    x, y,
                                    Constant(0)
                                )
                            )
                        ),
                        y
                    )
                ),
                x
            )
        )
    ),
    $var0
)
```

**Expected behavior**  
No exception is thrown, correct output.

**Version info**
- .NET Core / .NET Framework version: 4.8
- Version: NuGet 3.2.54

**Comment by zspitz** [comment]
Thanks for the bug report.

I've managed to reproduce with this:
```csharp
Expression<Func<Expression<Func<Expression<Func<string>>>>>> expr = () => () => () => "";
var s = expr.ToString("DebugView");
```
and am working on a fix.

However, I see another issue:  The built-in DebugView reports the unnamed variable as being of type `SomeType`, but the factory method calls report it as of type `TestContainer`. Can you confirm one way or the other? Could you include also the code which actually creates the expression?

**Comment by zspitz** [comment]
@avonwyss The latest version has the fix.

**Comment by avonwyss** [comment]
@zspitz Thanks for the fast fix! Sorry for not yet replying to your question. The `TestContainer` should have been `SomeType` also; I anonymized that part (some of the calls in the sample were against a generic interface implemented by `TestContainer` which was pretty noisy).
